// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvmBg5PVN-NgiQdGRmlBb9l_G_i7-Efns',
    appId: '1:608353264911:web:012318ef8b2ee384120a7a',
    messagingSenderId: '608353264911',
    projectId: 'detastore-14262',
    authDomain: 'detastore-14262.firebaseapp.com',
    databaseURL: 'https://detastore-14262-default-rtdb.firebaseio.com',
    storageBucket: 'detastore-14262.firebasestorage.app',
    measurementId: 'G-MZMRZDY0FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD97M_I1R4-FHaAQudrLMvRO1JcamdhEMo',
    appId: '1:608353264911:android:02dabdaff0282494120a7a',
    messagingSenderId: '608353264911',
    projectId: 'detastore-14262',
    databaseURL: 'https://detastore-14262-default-rtdb.firebaseio.com',
    storageBucket: 'detastore-14262.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvmBg5PVN-NgiQdGRmlBb9l_G_i7-Efns',
    appId: '1:608353264911:web:c36f6e69543ed262120a7a',
    messagingSenderId: '608353264911',
    projectId: 'detastore-14262',
    authDomain: 'detastore-14262.firebaseapp.com',
    databaseURL: 'https://detastore-14262-default-rtdb.firebaseio.com',
    storageBucket: 'detastore-14262.firebasestorage.app',
    measurementId: 'G-M27Q6R9M5C',
  );
}
